### ISSUE TITLE
提示：微软云edge-tts服务器维护中，请耐心等待

### ISSUE THREAD

**Issue by markringo** [swordswind/edge_tts_ai_voice_box#1]
是不是edge-tts下线了? 如果未来碰到这种情况，在哪里配置更新后的服务器URL？

**Comment by swordswind** [comment]
本软件仅支持edge-tts，不支持其他url。edge-tts已下线，请执行pip install edge-tts --upgrade升级到最新版

**Comment by swordswind** [comment]
本软件仅支持edge-tts，不支持其他url。edge-tts旧版已下线，请执行pip install edge-tts --upgrade升级到最新版

**Comment by markringo** [comment]
> 本软件仅支持edge-tts，不支持其他url。edge-tts旧版已下线，请执行pip install edge-tts --upgrade升级到最新版

解决了，谢谢

**Comment by swordswind** [comment]
好的
